language: java
os: linux
jdk: oraclejdk8
git:
  depth: false # https://stackoverflow.com/a/51727114/3714539
before_install:
  - git fetch --tags
  - source scripts/setup-build-tools.sh
script: scripts/travis.sh
addons:
  apt:
    update: true
stages:
  - name: test
  - name: release-snapshot
    if: (branch = master AND type = push) AND (tag IS NOT present)
  - name: release
    if: tag IS present
  - name: upload-launcher
    if: tag IS present
  - name: upload-launcher-gh-pages
    if: tag IS present
  - name: update-versioned-docs
    if: tag IS present
  - name: update-website
    if: (branch = master AND type = push) OR (tag IS present)
jobs:
  include:
    - env: SCALA_VERSION=2.12 BOOTSTRAP=1
    - env: SCALA_VERSION=2.13
      sudo: required
      services: docker
    - env: SCALA_VERSION=2.12
      sudo: required
      services: docker
    - env: SCALA_VERSION=2.12
      jdk: openjdk11
      script: bin/sbt scala212 test:compile testsJVM/test
    - env: SCALA_VERSION=2.11
      sudo: required
      services: docker
    - env: SCALA_VERSION=2.12 NATIVE=1
      before_script: curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
    - env: SCALA_VERSION=2.12 SCALA_JS=1
    - name: "Website"
      script: scripts/update-website.sh
    - name: "Pants"
      # Sanity check for Pants build path.
      script: cd modules && ./pants run cli/src/main/scala-2.12:coursier-cli -- fetch --help
    - stage: release-snapshot
      env: DUMMY_PROGUARD=1
      script: bin/sbt ci-release
    - stage: release
      # cli/publishLocal so that proguard runs before any publishing
      script: bin/sbt cli/publishLocal ci-release
    - stage: upload-launcher
      env: UPLOAD_LAUNCHER=1 # unused from the script, just to know what the job does from the Travis UI
      script: scripts/upload-launcher.sh
    - stage: upload-launcher-gh-pages
      script: scripts/upload-launcher-gh-pages.sh
    - stage: update-versioned-docs
      script: scripts/update-versioned-docs.sh
    - stage: update-website
      env: PUSH_WEBSITE=1
      script: scripts/update-website.sh
branches:
  only:
  - master
  - /^v\d+\.\d+.*$/ # tagged versions
cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.cache
